<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DevFlow.Common.Application\DevFlow.Common.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
      <PackageReference Include="AspNetCore.HealthChecks.Redis" />
      <PackageReference Include="EFCore.NamingConventions" />
      <PackageReference Include="MassTransit" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
      <PackageReference Include="Scrutor" />
    </ItemGroup>

</Project>
