<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DevFlow.Common.Application\DevFlow.Common.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
      <PackageReference Include="AspNetCore.HealthChecks.Redis" />
      <PackageReference Include="MassTransit" />
      <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>

</Project>
