<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    
    <ItemGroup Label="All">
        <PackageVersion Include="SonarAnalyzer.CSharp" Version="9.24.0.89429" />
    </ItemGroup>
    
    <ItemGroup Label="API" >
        <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8"/>
    </ItemGroup>
</Project>