<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Common\DevFlow.Common.Presentation\DevFlow.Common.Presentation.csproj" />
      <ProjectReference Include="..\DevFlow.Modules.Workspaces.Application\DevFlow.Modules.Workspaces.Application.csproj" />
    </ItemGroup>

</Project>
