<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DevFlow.Common.Domain\DevFlow.Common.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="Serilog" />
    </ItemGroup>

</Project>
