<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Common\DevFlow.Common.Infrastructure\DevFlow.Common.Infrastructure.csproj" />
      <ProjectReference Include="..\DevFlow.Modules.Workspaces.Application\DevFlow.Modules.Workspaces.Application.csproj" />
      <ProjectReference Include="..\DevFlow.Modules.Workspaces.Domain\DevFlow.Modules.Workspaces.Domain.csproj" />
      <ProjectReference Include="..\DevFlow.Modules.Workspaces.Presentation\DevFlow.Modules.Workspaces.Presentation.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Database\Configurations\" />
      <Folder Include="Workspaces\" />
    </ItemGroup>

</Project>
